os: unstable

install:
  # Install InnoSetup and add to path
  # Copied from
  # https://github.com/Phonations/Joker/blob/master/appveyor.yml
  - choco install -y InnoSetup
  - choco install -y nuget.commandline
  
shallow_clone: true

build_script:
  - nuget restore
  - msbuild /p:Configuration="Release"  /p:Targets="Build" /verbosity:quiet  /p:BuildInParallel=true /m 

test_script:
#  - "pip freeze"
# Disable pytest, because appveyor has problems with relative imports ??!
  - "%WITH_COMPILER% %PYTHON%/python setup.py test"

after_test:

  # Create InnoSetup installers
  # Set InnoSetup path here, in case it is missing.
  - set PATH="C:\Program Files (x86)\Inno Setup 5";%PATH%
  - iscc Setup\\win7_innosetup.iss

artifacts:
  # Archive the generated wheel package in the ci.appveyor.com build report.
  - path: dist\*
  # InnoSetup files
  - path: Output\*

deploy:
  provider: GitHub
  auth_token:
    secure: biglongtokenherehere
  artifact: /.*\.exe/
  draft: true
  prerelease: true
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only